# Generated by Django 3.2.17 on 2023-02-04 10:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.SlugField(verbose_name='Имя сервиса')),
            ],
            options={
                'verbose_name': 'Сервис',
                'verbose_name_plural': 'Сервисы',
            },
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.SlugField(verbose_name='Slug статуса')),
            ],
            options={
                'verbose_name': 'Статус',
                'verbose_name_plural': 'Статусы',
            },
        ),
        migrations.CreateModel(
            name='ServiceStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(verbose_name='Текстовое описание состояния')),
                ('date_time', models.DateTimeField(auto_now_add=True, verbose_name='Дата обновления статуса')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status', to='services.service', verbose_name='Сервис')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service', to='services.status', verbose_name='Статус')),
            ],
            options={
                'verbose_name': 'Cтатус сервиса',
                'verbose_name_plural': 'Статусы сервисов',
            },
        ),
    ]
