# Generated by Django 3.2.17 on 2023-02-04 11:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_auto_20230204_1617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicestatus',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status', to='services.service', verbose_name='Сервис'),
        ),
        migrations.AlterField(
            model_name='servicestatus',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service', to='services.status', verbose_name='Статус'),
        ),
    ]
