# Generated by Django 3.2.17 on 2023-02-04 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_auto_20230204_1618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicestatus',
            name='date_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата обновления состояния'),
        ),
    ]
