# Generated by Django 3.2.23 on 2023-11-12 08:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название')),
                ('status', models.CharField(choices=[('работает', 'работает'), ('не работает', 'не работает'), ('нестабильно', 'нестабильно')], default='работает', max_length=50, verbose_name='Состояние')),
                ('description', models.TextField(verbose_name='Описание')),
            ],
            options={
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='StatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=50, verbose_name='Состояние')),
                ('last_modified', models.DateTimeField(auto_now_add=True, verbose_name='Дата изменения')),
                ('start_time', models.DateTimeField(blank=True, null=True, verbose_name='Время начала недоступности сервиса')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='Время окончания недоступности сервиса')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='api.service', verbose_name='Название')),
            ],
            options={
                'ordering': ('-id',),
            },
        ),
    ]
