# Generated by Django 4.2.7 on 2023-11-15 08:45

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Service",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.CharField(max_length=50, unique=True)),
                (
                    "name",
                    models.CharField(
                        max_length=30, unique=True, verbose_name="Название"
                    ),
                ),
                (
                    "url",
                    models.URLField(
                        blank=True,
                        null=True,
                        validators=[django.core.validators.URLValidator],
                        verbose_name="Ссылка",
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Описание"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активность"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="дата создания сервиса"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ServiceState",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("Работает", "working"),
                            ("Не работает", "not working"),
                            ("Работает нестабильно", "works unstable"),
                            ("Нет данных", "no data"),
                        ],
                        default="Нет данных",
                        max_length=20,
                        verbose_name="Статус сервиса",
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Описание"
                    ),
                ),
                (
                    "datetime",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания записи состояния"
                    ),
                ),
                (
                    "relevance",
                    models.BooleanField(default=True, verbose_name="Актуальность"),
                ),
                (
                    "service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="service_state",
                        to="backend.service",
                        verbose_name="Сервис",
                    ),
                ),
            ],
        ),
    ]
