# Generated by Django 4.1.6 on 2023-02-03 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Name')),
                ('state', models.SmallIntegerField(choices=[(1, 'WORKING'), (2, 'NOT WORKING'), (3, 'UNSTABLE')], verbose_name='State')),
                ('description', models.TextField(max_length=1000, verbose_name='Description')),
            ],
        ),
    ]
