# Generated by Django 4.1.6 on 2023-02-03 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='slug_name',
            field=models.SlugField(default=1, max_length=255, unique=True, verbose_name='Slugified name'),
            preserve_default=False,
        ),
    ]
