# Generated by Django 4.1.6 on 2023-02-03 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_service_slug_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='service',
            name='slug_name',
            field=models.SlugField(max_length=255, verbose_name='Slugified name'),
        ),
    ]
