# Generated by Django 4.1.3 on 2023-02-06 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_service_created_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='service',
            options={'verbose_name': 'Service', 'verbose_name_plural': 'Services'},
        ),
        migrations.AddIndex(
            model_name='service',
            index=models.Index(fields=['slug_name'], name='core_servic_slug_na_612584_idx'),
        ),
        migrations.AddIndex(
            model_name='service',
            index=models.Index(fields=['-created_at'], name='core_servic_created_cf26f0_idx'),
        ),
    ]
