# Generated by Django 3.2 on 2023-02-02 15:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, unique=True, verbose_name='Название сервиса')),
            ],
            options={
                'verbose_name': 'Сервис',
                'verbose_name_plural': 'Сервисы',
            },
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condition', models.CharField(choices=[('up', 'up'), ('down', 'down'), ('unstable', 'unstable')], max_length=8, verbose_name='Состояние')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Время обновления')),
                ('service', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='statuses', to='services.service', verbose_name='Сервис')),
            ],
        ),
    ]
