# Generated by Django 3.2 on 2023-02-02 16:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_status_service_one_to_many'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='status',
            options={'verbose_name': 'Статус', 'verbose_name_plural': 'Статусы'},
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condition', models.CharField(choices=[('up', 'up'), ('down', 'down'), ('unstable', 'unstable')], max_length=8, verbose_name='Состояние')),
                ('timestamp', models.DateTimeField(verbose_name='Время обновления')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='old_statuses', to='services.service', verbose_name='Сервис')),
            ],
        ),
    ]
