# Generated by Django 3.2 on 2023-02-03 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_create_log_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='status',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
    ]
