# Generated by Django 3.0.5 on 2023-01-11 17:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Название сервиса')),
                ('description', models.TextField(blank=True, max_length=350, null=True, verbose_name='Описание')),
            ],
        ),
        migrations.CreateModel(
            name='TimeStamps',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_stamp', models.DateTimeField()),
                ('status', models.CharField(choices=[(1, 'working'), (2, 'unstable'), (3, 'down')], max_length=30, verbose_name='Состояние сервиса')),
                ('description', models.TextField(blank=True, max_length=350, null=True, verbose_name='Описание')),
                ('service', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='timestamps', to='api.Services')),
            ],
        ),
    ]
