# Generated by Django 3.0.5 on 2023-01-11 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timestamps',
            name='time_stamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
