# Generated by Django 3.2.16 on 2023-01-12 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20230111_2250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timestamps',
            name='status',
            field=models.CharField(choices=[('working', 'working'), ('unstable', 'unstable'), ('down', 'down')], max_length=30, verbose_name='Состояние сервиса'),
        ),
    ]
