"""create table Statuses2

Revision ID: 0783591a09e4
Revises: 6d0dfdd4af71
Create Date: 2023-02-05 18:59:46.475187

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0783591a09e4'
down_revision = '6d0dfdd4af71'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
