"""create table statuses

Revision ID: 2bd2f844a14c
Revises: f84e1f7104a9
Create Date: 2023-02-05 19:09:11.343248

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2bd2f844a14c'
down_revision = 'f84e1f7104a9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
