"""create table statuses

Revision ID: 599dc2b5aede
Revises: ef3e11f7c7ba
Create Date: 2023-02-05 19:55:39.168108

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '599dc2b5aede'
down_revision = 'ef3e11f7c7ba'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
