"""create table statuses

Revision ID: 5b716aa28dc7
Revises: 599dc2b5aede
Create Date: 2023-02-05 19:57:31.755180

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5b716aa28dc7'
down_revision = '599dc2b5aede'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('services_statuses_list',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Integer(), nullable=False),
    sa.Column('datetime', sa.DateTime(), nullable=False)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('services_statuses_list')
    # ### end Alembic commands ###
