"""create table Statuses

Revision ID: 6d0dfdd4af71
Revises: f7a184f18880
Create Date: 2023-02-05 18:49:16.821475

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6d0dfdd4af71'
down_revision = 'f7a184f18880'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
