"""create table Status

Revision ID: 9249a174fd6c
Revises: d32c53c8c2cc
Create Date: 2023-02-05 15:49:08.922353

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9249a174fd6c'
down_revision = 'd32c53c8c2cc'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
