"""create table Status

Revision ID: 996d32a0a701
Revises: db8cd60f54a3
Create Date: 2023-02-05 15:39:38.504745

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '996d32a0a701'
down_revision = 'db8cd60f54a3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
