"""create table Status

Revision ID: d32c53c8c2cc
Revises: 996d32a0a701
Create Date: 2023-02-05 15:39:43.858078

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd32c53c8c2cc'
down_revision = '996d32a0a701'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
