"""create table Status

Revision ID: d7ce76b9f90c
Revises: f550e61d7543
Create Date: 2023-02-05 15:39:15.784947

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd7ce76b9f90c'
down_revision = 'f550e61d7543'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('services_status_list', 'name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('services_status_list', sa.Column('name', sa.VARCHAR(length=25), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
