"""create table Status

Revision ID: db8cd60f54a3
Revises: d7ce76b9f90c
Create Date: 2023-02-05 15:39:33.311684

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'db8cd60f54a3'
down_revision = 'd7ce76b9f90c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
