"""create table statuses

Revision ID: ef3e11f7c7ba
Revises: 2bd2f844a14c
Create Date: 2023-02-05 19:11:14.758328

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ef3e11f7c7ba'
down_revision = '2bd2f844a14c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('services_statuses_list',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Unicode(length=25), nullable=False),
    sa.Column('datetime', sa.DateTime(), nullable=False)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('services_statuses_list')
    # ### end Alembic commands ###
