"""create table Status

Revision ID: f550e61d7543
Revises: b09e09bbf433
Create Date: 2023-02-05 15:37:51.716238

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f550e61d7543'
down_revision = 'b09e09bbf433'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'services_list', ['id'])
    op.create_unique_constraint(None, 'services_status_list', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'services_status_list', type_='unique')
    op.drop_constraint(None, 'services_list', type_='unique')
    # ### end Alembic commands ###
