"""create table Statuses

Revision ID: f7a184f18880
Revises: f12f30f03aa4
Create Date: 2023-02-05 18:47:45.910010

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f7a184f18880'
down_revision = 'f12f30f03aa4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
