"""create table Statuses2

Revision ID: f84e1f7104a9
Revises: 0783591a09e4
Create Date: 2023-02-05 19:01:03.774769

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f84e1f7104a9'
down_revision = '0783591a09e4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
